server:
  port: 8070
#  servlet:
#    context-path: /rms
spring:
  main:
    banner-mode: 'off'
  #  mvc:
  #    servlet:
  #      path: /api

  datasource:
    driver-class-name: org.postgresql.Driver
    #type: com.zaxxer.hikari.HikariDataSource
    ## default connection pool
    #hikari:
    #  connectionTimeout: 20000
    #  maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/rms
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        default_schema: rms_core
    format_sql: true
    show-sql: true

    mvc:
    pathmatch:
    matching-strategy:
      ANT_PATH_MATCHER

#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.xml
#


  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public



